Jusqu'ici nous avons manipuler des données avec des listes ou des dictionnaires

In [1]:
countryDict = {'France':70,'Angleterre':55,'Allemagne':85}
print(countryDict)

{'France': 70, 'Angleterre': 55, 'Allemagne': 85}


In [2]:
countryList = [['France',70],['Angleterre',55],['Allemagne',85]]
print(countryList)

[['France', 70], ['Angleterre', 55], ['Allemagne', 85]]


Pas adapté pour stoker des données pour une même dimension (pour un pays avoir la pop, le PIB, l'IDH))

<b> Créer un tableau </b>

In [3]:
import numpy as np
pays = np.array([ 
    ['France', 'Angleterre', 'Allemagne'], #Nom pays
    [70, 55, 85],                          #Population en millions
    [0.901, 0.922, 0.936],                 #IDH
    [2091,2077,3045]                       #PIB
])
print(pays)

[['France' 'Angleterre' 'Allemagne']
 ['70' '55' '85']
 ['0.901' '0.922' '0.936']
 ['2091' '2077' '3045']]


<b>Sélectionner des valeurs dans un tableau (slicing)</b>

In [4]:
pays[1]

array(['70', '55', '85'], dtype='<U10')

In [5]:
pays[1,1]

'55'

In [6]:
pays[:,1]

array(['Angleterre', '55', '0.922', '2077'], dtype='<U10')

In [7]:
pays[1:3,:]

array([['70', '55', '85'],
       ['0.901', '0.922', '0.936']], dtype='<U10')

In [8]:
pays[:,1:3]

array([['Angleterre', 'Allemagne'],
       ['55', '85'],
       ['0.922', '0.936'],
       ['2077', '3045']], dtype='<U10')

<b>Faire des opérations dans un tableau</b>

In [9]:
dataPays = pays[1:,:]
print(dataPays)
#dataPays[1,1] - 1
#.astype(float)
#pays

[['70' '55' '85']
 ['0.901' '0.922' '0.936']
 ['2091' '2077' '3045']]


In [10]:
dataPays = dataPays.astype(float)
dataPays

array([[7.000e+01, 5.500e+01, 8.500e+01],
       [9.010e-01, 9.220e-01, 9.360e-01],
       [2.091e+03, 2.077e+03, 3.045e+03]])

In [11]:
np.set_printoptions(suppress=True)
dataPays

array([[  70.   ,   55.   ,   85.   ],
       [   0.901,    0.922,    0.936],
       [2091.   , 2077.   , 3045.   ]])

In [12]:
dataPays*2

array([[ 140.   ,  110.   ,  170.   ],
       [   1.802,    1.844,    1.872],
       [4182.   , 4154.   , 6090.   ]])

In [13]:
pib2018 = np.array([2091,2077,3045])
pib2019 = np.array([2325,2101,3500])
pib20182019 = pib2018 + pib2019
pib20182019

array([4416, 4178, 6545])

<b>Analyser un tableau</b>

In [14]:
dataPays.sum()
dataPays[2,:].sum() #Sommes des PIB

7213.0

In [15]:
print(dataPays[2,:].min())
print(dataPays[2,:].max())
print(dataPays[2,:].mean())

2077.0
3045.0
2404.3333333333335


In [16]:
bestPibIndex = dataPays[2,:].argmax()
worstPibIndex = dataPays[2,:].argmin()
print(bestPibIndex,worstPibIndex)

2 1


In [17]:
print('le pays le plus riche : '+pays[0,bestPibIndex])
print('le pays le moins riche : '+pays[0,worstPibIndex])

le pays le plus riche : Allemagne
le pays le moins riche : Angleterre


In [18]:
tab1 = np.array([1,2,3,4])
tab2 = np.array([1,7,3,4])
np.equal(tab1, tab2)

array([ True, False,  True,  True])

<b> Manipuler un tableau </b>

In [19]:
dataPays[1,1] = 0
dataPays

array([[  70.   ,   55.   ,   85.   ],
       [   0.901,    0.   ,    0.936],
       [2091.   , 2077.   , 3045.   ]])

In [20]:
np.concatenate((pib2018, pib2019), axis=0)

array([2091, 2077, 3045, 2325, 2101, 3500])

In [21]:
dataPays = np.array([
    [1, np.nan, 3],                          
    [1, 2, 3],                 
    [1, 2, 3]
])
print(dataPays)

[[ 1. nan  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]


In [22]:
dataPays*2

array([[ 2., nan,  6.],
       [ 2.,  4.,  6.],
       [ 2.,  4.,  6.]])

In [23]:
np.nan_to_num(dataPays)

array([[1., 0., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [24]:
Pays1 = np.array([
    [1, 2],                          
    [3, 4],
])
Pays2 = np.array([
    [5, 6],                          
    [7, 8],
])

print(Pays1*Pays2)
print(Pays1+Pays2)

#numpy peut également être utilisé pour du calcul matriciel (numpy.dot, array.T)

[[ 5 12]
 [21 32]]
[[ 6  8]
 [10 12]]


<b>Le module arrange<b>

In [25]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])